# Generated by Django 6.0 on 2026-01-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalBank', '0003_atmcard_pin_bankotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmcard',
            name='pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
