# Generated by Django 5.2.7 on 2025-12-15 09:07

import Pan_App.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Aadhar_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_no', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to=Pan_App.models.pan_photo_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aadhar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pan', to='Aadhar_App.aadhar')),
            ],
        ),
    ]
