# Generated by Django 6.0 on 2026-01-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YourBank', '0003_atmcard_pin_bankotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmcard',
            name='otp_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='atmcard',
            name='pin',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
