# Generated by Django 6.0 on 2026-01-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aadhar_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aadharotp',
            old_name='expires_at',
            new_name='expiry',
        ),
        migrations.RenameField(
            model_name='aadharotp',
            old_name='used',
            new_name='verified',
        ),
        migrations.AddField(
            model_name='aadharotp',
            name='reason',
            field=models.CharField(default='Upay_BankLink', max_length=50),
        ),
        migrations.AlterField(
            model_name='aadharotp',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
    ]
