# Generated by Django 6.0 on 2026-01-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aadhar_App', '0002_rename_expires_at_aadharotp_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadharotp',
            name='reason',
            field=models.CharField(default='Aadhar_Verifiation', max_length=50),
        ),
    ]
