# Generated by Django 6.0 on 2026-01-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upayuser',
            name='bank_app',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='upayuser',
            name='customer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
